### ISSUE TITLE
jekyllのハイライト

### ISSUE THREAD

**Issue by himkt** [open-klis/open-klis.github.io#3]
デプロイ先では問題ない(http://open-klis.github.io/git/2015/06/05/git-training.html)けどローカルではjekyll sに失敗する

**Comment by makky3939** [comment]
shellのハイライトはローカルでも効いている気がするのですが、どの部分のハイライトを指していますか？ 
![j](https://cloud.githubusercontent.com/assets/4876459/8018484/2576db32-0c59-11e5-8a19-91e5d20fa1e3.png)

**Comment by himkt** [comment]
こちらの環境では、そもそもjekyll sがfailするのでgemの問題ですかね

**Comment by makky3939** [comment]
ちなみにどんなエラーなんですか？
それと、Gemfileを作ってgem 'jekyll'しておきたい気がするのですが、GitHubPages側で問題あったりしますか？

**Comment by himkt** [comment]
There was an error highlighting your code:

# 名前を設定
git config --global user.name "your name"
# メールアドレスを設定
git config --global user.email "your email address"

While attempting to convert the above code, Pygments.rb returned an unacceptable value.
This is usually a timeout problem solved by running `jekyll build` again.
  Liquid Exception: Pygments.rb returned an unacceptable value when attempting to highlight some code. in _posts/2015-06-05-git-training.markdown
jekyll 2.5.3 | Error:  Pygments.rb returned an unacceptable value when attempting to highlight some code.


Gemfileは作成しておきます

**Comment by himkt** [comment]
ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '0000-00-00': Post '/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the filename.

bundle execからjekyllを読んだら別のバクを踏んだ。おしまいだ。

**Comment by polamjag** [comment]
`_config.yml` にこれ追記で直ります 

```yaml
exclude: ["vendor"]
```

e.g. https://github.com/ITFDJ/itfdj.github.io/blob/master/_config.yml#L13

**Comment by himkt** [comment]
解決しました。ありがとうございます。
@makky3939  https://github.com/open-klis/open-klis.github.io/issues/3#issuecomment-109562373 これってまっきーの環境では再現しない感じですか

**Comment by makky3939** [comment]
再現はできてないです;;

**Comment by himkt** [comment]
OSXインストールしなおしたら一つめのバグも無くなりました
gem jekyllはpython3系の環境では使えない(Pygments.rbがpython3系に対応していない)ようで、これが問題だったっぽいです。

また、bundle install時はインストール先をbundleに指定するようにしてください
```ruby
exclude: ["bundle"]
```
しています
